"""Corrección de modelos

Revision ID: 05a58145ee6d
Revises: 
Create Date: 2025-01-30 07:51:41.502922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a58145ee6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('profesor_asignado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cursos'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('presente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_asistencias_id_curso_cursos')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_asistencias_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asistencias'))
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_matriculas_id_curso_cursos')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_matriculas_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas'))
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_notificaciones_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones'))
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_tareas_id_curso_cursos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tareas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    op.drop_table('notificaciones')
    op.drop_table('matriculas')
    op.drop_table('asistencias')
    op.drop_table('usuarios')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    op.drop_table('cursos')
    # ### end Alembic commands ###
