"""Actualización de modelos

Revision ID: 116b9b7a399e
Revises: 05a58145ee6d
Create Date: 2025-01-30 12:55:10.765135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116b9b7a399e'
down_revision: Union[str, None] = '05a58145ee6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencias', sa.Column('estado', sa.Enum('presente', 'ausente', 'tarde', 'justificada', name='estadoasistencia'), nullable=False))
    op.drop_column('asistencias', 'presente')
    op.create_foreign_key(op.f('fk_cursos_profesor_asignado_usuarios'), 'cursos', 'usuarios', ['profesor_asignado'], ['id'])
    op.add_column('matriculas', sa.Column('fecha_matricula', sa.Date(), nullable=False))
    op.add_column('matriculas', sa.Column('estado', sa.Enum('activa', 'suspendida', 'finalizada', name='estadomatricula'), nullable=False))
    op.add_column('notificaciones', sa.Column('leida', sa.Boolean(), nullable=False))
    op.add_column('tareas', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('tareas', sa.Column('estado', sa.Enum('pendiente', 'entregada', 'calificada', name='estadotarea'), nullable=False))
    op.alter_column('tareas', 'fecha_entrega',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('administrador', 'profesor', 'estudiante', name='rol'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'rol',
               existing_type=sa.Enum('administrador', 'profesor', 'estudiante', name='rol'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tareas', 'fecha_entrega',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('tareas', 'estado')
    op.drop_column('tareas', 'fecha_creacion')
    op.drop_column('notificaciones', 'leida')
    op.drop_column('matriculas', 'estado')
    op.drop_column('matriculas', 'fecha_matricula')
    op.drop_constraint(op.f('fk_cursos_profesor_asignado_usuarios'), 'cursos', type_='foreignkey')
    op.add_column('asistencias', sa.Column('presente', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('asistencias', 'estado')
    # ### end Alembic commands ###
