"""empty message

Revision ID: ff65f1cd462b
Revises: 
Create Date: 2025-02-06 19:10:39.829374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff65f1cd462b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'profesor', 'estudiante', name='rol'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('profesor_asignado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_asignado'], ['usuarios.id'], name=op.f('fk_cursos_profesor_asignado_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cursos'))
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_notificaciones_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones'))
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('presente', 'ausente', 'tarde', 'justificada', name='estado'), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_asistencias_id_curso_cursos')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_asistencias_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asistencias'))
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'suspendida', 'finalizada', name='estadomatricula'), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_matriculas_id_curso_cursos')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_matriculas_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas'))
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'entregada', 'calificada', name='estadotarea'), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], name=op.f('fk_tareas_id_curso_cursos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tareas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    op.drop_table('matriculas')
    op.drop_table('asistencias')
    op.drop_table('notificaciones')
    op.drop_table('cursos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
